# Generated by Django 6.0.6 on 2026-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_message_file_name_message_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
